### ISSUE TITLE
DynamicSchema.Builder fails at .build() when using protobuf-java-2.6.1

### ISSUE THREAD

**Issue by Ganet** [os72/protobuf-dynamic#2]
I get a NoSuchMethod exception at line 203 in Dynamic Schema:

List<String> dependencyList = fdProto.getDependencyList();

But if I change it for:

ProtocolStringList dependencyList = fdProto.getDependencyList();

Everything works correctly. Is this normal or just my issue? I don't know if this matters but I am using Java 8.

I can do a pull request if you like with the necessary changes to get it working with protobuf-java-2.6.1 .

**Comment by os72** [comment]
Thanks, will look into it. Does your change work with 2.4.1?

**Comment by Ganet** [comment]
Yes, it worked fine with 2.4.1 when I tried.

Kind Regards

**Comment by os72** [comment]
I don't think this works in 2.4.1, ProtocolStringList is undefined there. I also don't see why it would fail in 2.6.1 because:
public interface ProtocolStringList extends List<String>
https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/ProtocolStringList

I re-verified it works for me with 2.6.1. I also doubt it has anything to do w Java8. Can you describe in more detail how it fails for you, with full stack trace?

**Comment by Ganet** [comment]
I am using these Maven dependencies in my project:

		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>2.6.1</version>
		</dependency>
		<dependency>
			<groupId>com.github.os72</groupId>
			<artifactId>protobuf-dynamic</artifactId>
			<version>0.9.1</version>
		</dependency>

Then a very simple test like:

        final DynamicSchema.Builder schemaBuilder = DynamicSchema.newBuilder();
        schemaBuilder.setName("INSTRUMENT_L1_PRICESchemaDynamic.proto");

        final MessageDefinition.Builder msgDef =
                MessageDefinition.newBuilder("INSTRUMENT_L1_PRICE")
                        .addField("required", "double", "LOW_PRICE", 1)
                        .addField("required", "double", "HIGH_PRICE", 2)
                        .addField("required", "double", "BID_PRICE", 3)
                        .addField("required", "double", "ASK_PRICE", 4)
                        .addField("required", "int32", "BID_SIZE", 5)
                        .addField("required", "int32", "ASK_SIZE", 6)
                        .addField("required", "double", "VWAP", 7)
                        .addField("required", "double", "PCT_CHANGE", 8)
                        .addField("required", "double", "OPEN_PRICE", 9)
                        .addField("required", "string", "INSTRUMENT_CODE", 10);

        schemaBuilder.addMessageDefinition(msgDef.build());
        try{
            final DynamicSchema schema = schemaBuilder.build();
        } catch(Exception e){
            e.printStackTrace();
        }

Would give me this error and stack trace:

<code>
java.lang.NoSuchMethodError: com.google.protobuf.DescriptorProtos$FileDescriptorProto.getDependencyList()Ljava/util/List;
	at com.github.os72.protobuf.dynamic.DynamicSchema.init(DynamicSchema.java:203)
	at com.github.os72.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:176)
	at com.github.os72.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:42)
	at com.github.os72.protobuf.dynamic.DynamicSchema$Builder.build(DynamicSchema.java:269)
<code>

This is an odd issue indeed... But as I said in my initial comment, if I modify manually line line 203 in Dynamic Schema to be ProtocolStringList dependencyList = fdProto.getDependencyList() I get no problems at all.

**Comment by os72** [comment]
Do the unit tests pass for you? (change 2.4.1 -> 2.6.1, two places in pom.xml) They work for me
And could you try with Java7?

**Comment by Ganet** [comment]
With 2.4.1 unit tests work completely fine in both Java 7 and 8.

I changed 2.4.1 for 2.6.1 in dependencies and also in plugins for protoc-jar-maven-plugin (2.6.1.4) and one of the unit tests now fails (Java 7 and 8 as well):

 --- testBasic ---
types: [Person]
enums: []
file {
  name: "PersonSchemaDynamic.proto"
  message_type {
    name: "Person"
    field {
      name: "id"
      number: 1
      label: LABEL_REQUIRED
      type: TYPE_INT32
    }
    field {
      name: "name"
      number: 2
      label: LABEL_REQUIRED
      type: TYPE_STRING
    }
    field {
      name: "email"
      number: 3
      label: LABEL_OPTIONAL
      type: TYPE_STRING
    }
  }
}

id: 1
name: "Alan Turing"
email: "at@sis.gov.uk"


java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.

	at com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:192)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:301)
	at com.google.protobuf.TextFormat$Printer.access$400(TextFormat.java:273)
	at com.google.protobuf.TextFormat.print(TextFormat.java:76)
	at com.google.protobuf.TextFormat.printToString(TextFormat.java:143)
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:79)
	at com.github.os72.protobuf.dynamic.DynamicSchemaTest.testBasic(DynamicSchemaTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by os72** [comment]
No, that's just protobuf version incompatibility, generated code vs runtime. Make sure to clean install

**Comment by Ganet** [comment]
Sorry. my mistake. I forgot to run clean install.

I also copy pasted my example to your unit tests and it works fine there.

Therefore, I have no idea about what is wrong with my project. But I can't get to use protobuf-java 2.6.1 and protobuf-dynamic 0.9.1 at the same time without getting the NoSuchMethod exception. I will look into it again and try to find out why I get this problem. However, the odd thing is modifying line 203 in DynamicSchema to be "ProtocolStringList dependencyList = fdProto.getDependencyList();" makes it work for some reason, even though ProtocolStringList extends List<String> and there should be no compatibility issues.

Thank you for your help and sorry for the nuisance, I will reply again if I figure out what's the issue.

**Comment by os72** [comment]
Could you capture your experiment isolated in a github repo? Then I can clone it and try to reproduce it

Your change shouldn't be required and also wouldn't be backward compatible, so we should dig further

**Comment by os72** [comment]
I moved my unit tests into a separate project with protobuf-dynamic as dependency and I'm able to reproduce the issue. Looking into it, I'd like to find a backward compatible solution..

**Comment by os72** [comment]
Implemented a fix, could you try 0.9.2-SNAPSHOT? If you confirm I'll publish 0.9.2
(BTW I also tried with 3.0.0-beta-1 and it seems to work)
Thanks!

**Comment by Ganet** [comment]
Hey, apologies for answering several days later, but I haven't been around until today. I am trying to use 0.9.2-SNAPSHOT but maven fails to resolve the dependency.

"The POM for com.github.os72:protobuf-dynamic:jar:0.9.2-SNAPSHOT is missing, no dependency information available"

Thanks for the hard work and the fix! I will test it as soon as I can resolve the dependency and I will give you feedback about it ;)

**Comment by os72** [comment]
SNAPSHOT isn't published, could you clone the repo and do a local clean install?

**Comment by Ganet** [comment]
Sure thing, I cloned it and installed it. It seems to work perfectly fine now!

Thanks again! :+1:

**Comment by os72** [comment]
Thanks for confirming, I've released 0.9.2 now. Thanks!
